# Generated by Django 6.0.5 on 2026-05-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
